export const PLAYER = {
  FETCH_PLAYBACK_DATA_REQUEST: 'FETCH_PLAYBACK_DATA_REQUEST',
  FETCH_PLAYBACK_DATA_SUCCESS: 'FETCH_PLAYBACK_DATA_SUCCESS',
  FETCH_PLAYBACK_DATA_FAILURE: 'FETCH_PLAYBACK_DATA_FAILURE',
  SET_VOLUME_REQUEST: 'SET_VOLUME_REQUEST',
  SET_VOLUME_SUCCESS: 'SET_VOLUME_SUCCESS',
  SET_VOLUME_FAILURE: 'SET_VOLUME_FAILURE',
  UPDATE_COUNTDOWN: 'UPDATE_COUNTDOWN',
  UPDATE_COUNTDOWN_SUCCESS: 'UPDATE_COUNTDOWN_SUCCESS',
  UPDATE_COUNTDOWN_FAILURE: 'UPDATE_COUNTDOWN_FAILURE'
}

export const AUTH = {
  GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT'
}